export const webSiteLabel = {
  webDespEN: 'Analyze languages used by visitors at tourist destinations.',
  webDespTH:
    'เว็บแอพพลิเคชันสำหรับวิเคราะห์ภาษาที่ใช้จากผู้มาเยือนในสถานที่ท่องเที่ยว',
  selectDestinationEN: 'Select a tourist destination',
  selectDestinationTH: 'เลือกสถานที่ท่องเที่ยวที่สนใจ',
  natureEN: 'NATURE',
  natureTH: 'ธรรมชาติ',
  artEN: 'ART&CULTURE',
  artENSimple: 'ART_CULTURE',
  artTH: 'ศิลปวัฒนธรรม',
  historicEN: 'HISTORIC',
  historicTH: 'ประวัติศาสตร์',
  modernEN: 'MODERN',
  modernTH: 'มนุษย์สร้างขึ้น',
  seeDetailEN: 'See Details',
  seeDetailTH: 'เข้าชม',
  languageUsedEN: 'Languages used by tourists at this place',
  languageUsedTH: 'ภาษาที่นักท่องเที่ยวใช้ในสถานที่แห่งนี้',
  inThePastEN: 'in the past',
  inThePastTH: 'ในระยะเวลา',
  timelineEN: 'Timeline',
  timelineTH: 'ช่วงเวลา',
  timeline24EN: '24 Hours',
  timeline24TH: '24 ชั่วโมงที่ผ่านมา',
  timeline48EN: '48 Hours',
  timeline48TH: '48 ชั่วโมงที่ผ่านมา',
  timeline7EN: '7 Days',
  timeline7TH: '7 วันที่ผ่านมา',
  timeline14EN: '14 Days',
  timeline14TH: '14 วันที่ผ่านมา',
  dataNotFoundEN: 'Please select different timeline or another location.',
  dataNotFoundTH: 'กรุณาเลือกช่วงเวลาหรือสถานที่อื่น ๆ ',
  locationNotFoundEN: 'No Location found',
  locationNotFoundTH: 'ไม่พบสถานที่ที่ต้องการ',
  locationNotFoundEN2:
    'Sorry, the location is not avaliable or no longer existed',
  locationNotFoundTH2: 'ไม่พบสถานที่ที่ต้องการ',
  loadingDataEN: 'Loading datas..',
  loadingDataTH: 'กำลังโหลดข้อมูล..',
  postsEN: 'posts',
  postsTH: 'โพสต์',
  lastUpdateOnEN: 'Last update on',
  lastUpdateOnTH: 'ข้อมูล ณ วันที่',
  backToEN: 'Back to',
  backToTH: 'กลับไปที่',
  exploreOtherLocationsEN: 'Explore other locations',
  exploreOtherLocationsTH: 'ไปยังสถานที่อื่น ๆ',
  includeThaiEN: 'Include Thai language',
  includeThaiTH: 'นับรวมภาษาไทย',
}
