CREATE TABLE language (
    language_id serial primary key ,
    language varchar,
    iso_code text,
    created_at timestamp not null ,
    created_by varchar not null ,
    updated_at timestamp,
    updated_by varchar
);

INSERT INTO language(language, iso_code, created_at, created_by) VALUES
 ('Afrikaans','af',now(),'System')
,('Albanian','sq',now(),'System')
,('Amharic','am',now(),'System')
,('Arabic','ar',now(),'System')
,('Armenian','hy',now(),'System')
,('Assamese','as',now(),'System')
,('Aymara','ay',now(),'System')
,('Azerbaijani','az',now(),'System')
,('Bambara','bm',now(),'System')
,('Basque','eu',now(),'System')
,('Belarusian','be',now(),'System')
,('Bengali','bn',now(),'System')
,('Bhojpuri','bho',now(),'System')
,('Bosnian','bs',now(),'System')
,('Bulgarian','bg',now(),'System')
,('Catalan','ca',now(),'System')
,('Cebuano','ceb',now(),'System')
,('Chinese (Simplified)','zh-CN',now(),'System')
,('Chinese (Simplified)','zh',now(),'System')
,('Chinese (Traditional)','zh-TW',now(),'System')
,('Corsican','co',now(),'System')
,('Croatian','hr',now(),'System')
,('Czech','cs',now(),'System')
,('Danish','da',now(),'System')
,('Dhivehi','dv',now(),'System')
,('Dogri','doi',now(),'System')
,('Dutch','nl',now(),'System')
,('English','en',now(),'System')
,('Esperanto','eo',now(),'System')
,('Estonian','et',now(),'System')
,('Ewe','ee',now(),'System')
,('Filipino (Tagalog)','fil',now(),'System')
,('Finnish','fi',now(),'System')
,('French','fr',now(),'System')
,('Frisian','fy',now(),'System')
,('Galician','gl',now(),'System')
,('Georgian','ka',now(),'System')
,('German','de',now(),'System')
,('Greek','el',now(),'System')
,('Guarani','gn',now(),'System')
,('Gujarati','gu',now(),'System')
,('Haitian Creole','ht',now(),'System')
,('Hausa','ha',now(),'System')
,('Hawaiian','haw',now(),'System')
,('Hebrew','he',now(),'System')
,('Hebrew','iw',now(),'System')
,('Hindi','hi',now(),'System')
,('Hmong','hmn',now(),'System')
,('Hungarian','hu',now(),'System')
,('Icelandic','is',now(),'System')
,('Igbo','ig',now(),'System')
,('Ilocano','ilo',now(),'System')
,('Indonesian','id',now(),'System')
,('Irish','ga',now(),'System')
,('Italian','it',now(),'System')
,('Japanese','ja',now(),'System')
,('Javanese','jv',now(),'System')
,('Javanese','jw',now(),'System')
,('Kannada','kn',now(),'System')
,('Kazakh','kk',now(),'System')
,('Khmer','km',now(),'System')
,('Kinyarwanda','rw',now(),'System')
,('Konkani','gom',now(),'System')
,('Korean','ko',now(),'System')
,('Krio','kri',now(),'System')
,('Kurdish','ku',now(),'System')
,('Kurdish (Sorani)','ckb',now(),'System')
,('Kyrgyz','ky',now(),'System')
,('Lao','lo',now(),'System')
,('Latin','la',now(),'System')
,('Latvian','lv',now(),'System')
,('Lingala','ln',now(),'System')
,('Lithuanian','lt',now(),'System')
,('Luganda','lg',now(),'System')
,('Luxembourgish','lb',now(),'System')
,('Macedonian','mk',now(),'System')
,('Maithili','mai',now(),'System')
,('Malagasy','mg',now(),'System')
,('Malay','ms',now(),'System')
,('Malayalam','ml',now(),'System')
,('Maltese','mt',now(),'System')
,('Maori','mi',now(),'System')
,('Marathi','mr',now(),'System')
,('Meiteilon (Manipuri)','mni-Mtei',now(),'System')
,('Mizo','lus',now(),'System')
,('Mongolian','mn',now(),'System')
,('Myanmar (Burmese)','my',now(),'System')
,('Nepali','ne',now(),'System')
,('Norwegian','no',now(),'System')
,('Nyanja (Chichewa)','ny',now(),'System')
,('Odia (Oriya)','or',now(),'System')
,('Oromo','om',now(),'System')
,('Pashto','ps',now(),'System')
,('Persian','fa',now(),'System')
,('Polish','pl',now(),'System')
,('Portuguese (Portugal, Brazil)','pt',now(),'System')
,('Punjabi','pa',now(),'System')
,('Quechua','qu',now(),'System')
,('Romanian','ro',now(),'System')
,('Russian','ru',now(),'System')
,('Samoan','sm',now(),'System')
,('Sanskrit','sa',now(),'System')
,('Scots Gaelic','gd',now(),'System')
,('Sepedi','nso',now(),'System')
,('Serbian','sr',now(),'System')
,('Sesotho','st',now(),'System')
,('Shona','sn',now(),'System')
,('Sindhi','sd',now(),'System')
,('Sinhala (Sinhalese)','si',now(),'System')
,('Slovak','sk',now(),'System')
,('Slovenian','sl',now(),'System')
,('Somali','so',now(),'System')
,('Spanish','es',now(),'System')
,('Sundanese','su',now(),'System')
,('Swahili','sw',now(),'System')
,('Swedish','sv',now(),'System')
,('Tagalog (Filipino)','tl',now(),'System')
,('Tajik','tg',now(),'System')
,('Tamil','ta',now(),'System')
,('Tatar','tt',now(),'System')
,('Telugu','te',now(),'System')
,('Thai','th',now(),'System')
,('Tigrinya','ti',now(),'System')
,('Tsonga','ts',now(),'System')
,('Turkish','tr',now(),'System')
,('Turkmen','tk',now(),'System')
,('Twi (Akan)','ak',now(),'System')
,('Ukrainian','uk',now(),'System')
,('Urdu','ur',now(),'System')
,('Uyghur','ug',now(),'System')
,('Uzbek','uz',now(),'System')
,('Vietnamese','vi',now(),'System')
,('Welsh','cy',now(),'System')
,('Xhosa','xh',now(),'System')
,('Yiddish','yi',now(),'System')
,('Yoruba','yo',now(),'System')
,('Zulu','zu',now(),'System');
